language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5

addons:
  apt:
    packages:
    - libqtwebkit-dev
    - xvfb

  code_climate:
    repo_token:
      secure: "cT2wvWS2Uk2trYGwZ38Qo9XWCeL+OOXH0lVmLfNb1Xy/tWAXycDdZsc9CN8igjhD+/cKvvh529/qdDm2PJnb1Hux1bxHSTuMuE2xQWlfJqaOR/IX0z96MbP1eITKjhGv9vccmIPdV3Rh/OQLeHkyqyHvXio9NXiARMJUZDTpRuA="

branches:
  only:
    - 1.0.x  # stable
    - master

install:
  - wget -c "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-x64-linux.tar.gz"
  - tar xvf ncbi-blast-2.6.0+-x64-linux.tar.gz
  - export PATH="ncbi-blast-2.6.0+/bin:$PATH"
  - gem install bundler && bundle

script: xvfb-run bundle exec rake spec

cache:
  directories:
    - vendor/bundle
    - ncbi-blast-2.6.0+

sudo: false
