
## Site variables for SEO
title: 'SequenceServer'
description: 'Use SequenceServer to pragmatically perform and interpret genomic comparisons using NCBI BLAST. SequenceServer accelerates your analyses so you can focus on the science.'
url: https://sequenceserver.com
production_url: https://sequenceserver.com


exclude: ['node_modules','.DS_Store','.git-ignore', '.ruby-version','.git/','Gemfile', 'Gemfile.lock', 'README.md']

collections:
  blog       :
    output    : true
    permalink : /:collection/:path/




## Plugins
plugins:
  - jekyll-seo-tag